ALTER TABLE "invoices"
ADD COLUMN "companyName" TEXT,
ADD COLUMN "companyEmail" TEXT,
ADD COLUMN "companyPhone" TEXT,
ADD COLUMN "companyWebsite" TEXT,
ADD COLUMN "companyAddressLine1" TEXT,
ADD COLUMN "companyAddressLine2" TEXT,
ADD COLUMN "companyCity" TEXT,
ADD COLUMN "companyProvince" TEXT,
ADD COLUMN "companyPostalCode" TEXT,
ADD COLUMN "companyCountry" TEXT,
ADD COLUMN "companyTaxNumber" TEXT,
ADD COLUMN "customerName" TEXT,
ADD COLUMN "customerCompanyName" TEXT,
ADD COLUMN "customerEmail" TEXT,
ADD COLUMN "customerPhone" TEXT,
ADD COLUMN "customerBillingAddressLine1" TEXT,
ADD COLUMN "customerBillingAddressLine2" TEXT,
ADD COLUMN "customerBillingCity" TEXT,
ADD COLUMN "customerBillingProvince" TEXT,
ADD COLUMN "customerBillingPostalCode" TEXT,
ADD COLUMN "customerBillingCountry" TEXT,
ADD COLUMN "customerShippingSameAsBilling" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "customerShippingAddressLine1" TEXT,
ADD COLUMN "customerShippingAddressLine2" TEXT,
ADD COLUMN "customerShippingCity" TEXT,
ADD COLUMN "customerShippingProvince" TEXT,
ADD COLUMN "customerShippingPostalCode" TEXT,
ADD COLUMN "customerShippingCountry" TEXT;

ALTER TABLE "estimates"
ADD COLUMN "companyName" TEXT,
ADD COLUMN "companyEmail" TEXT,
ADD COLUMN "companyPhone" TEXT,
ADD COLUMN "companyWebsite" TEXT,
ADD COLUMN "companyAddressLine1" TEXT,
ADD COLUMN "companyAddressLine2" TEXT,
ADD COLUMN "companyCity" TEXT,
ADD COLUMN "companyProvince" TEXT,
ADD COLUMN "companyPostalCode" TEXT,
ADD COLUMN "companyCountry" TEXT,
ADD COLUMN "companyTaxNumber" TEXT,
ADD COLUMN "customerName" TEXT,
ADD COLUMN "customerCompanyName" TEXT,
ADD COLUMN "customerEmail" TEXT,
ADD COLUMN "customerPhone" TEXT,
ADD COLUMN "customerBillingAddressLine1" TEXT,
ADD COLUMN "customerBillingAddressLine2" TEXT,
ADD COLUMN "customerBillingCity" TEXT,
ADD COLUMN "customerBillingProvince" TEXT,
ADD COLUMN "customerBillingPostalCode" TEXT,
ADD COLUMN "customerBillingCountry" TEXT,
ADD COLUMN "customerShippingSameAsBilling" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "customerShippingAddressLine1" TEXT,
ADD COLUMN "customerShippingAddressLine2" TEXT,
ADD COLUMN "customerShippingCity" TEXT,
ADD COLUMN "customerShippingProvince" TEXT,
ADD COLUMN "customerShippingPostalCode" TEXT,
ADD COLUMN "customerShippingCountry" TEXT;

UPDATE "invoices" AS i
SET
  "companyName" = c."companyName",
  "companyEmail" = c."email",
  "companyPhone" = c."phone",
  "companyWebsite" = c."website",
  "companyAddressLine1" = c."addressLine1",
  "companyAddressLine2" = c."addressLine2",
  "companyCity" = c."city",
  "companyProvince" = c."province",
  "companyPostalCode" = c."postalCode",
  "companyCountry" = c."country",
  "companyTaxNumber" = c."taxNumber",
  "customerName" = cu."name",
  "customerCompanyName" = cu."companyName",
  "customerEmail" = cu."email",
  "customerPhone" = cu."phone",
  "customerBillingAddressLine1" = cu."billingAddressLine1",
  "customerBillingAddressLine2" = cu."billingAddressLine2",
  "customerBillingCity" = cu."billingCity",
  "customerBillingProvince" = cu."billingProvince",
  "customerBillingPostalCode" = cu."billingPostalCode",
  "customerBillingCountry" = cu."billingCountry",
  "customerShippingSameAsBilling" = cu."shippingSameAsBilling",
  "customerShippingAddressLine1" = cu."shippingAddressLine1",
  "customerShippingAddressLine2" = cu."shippingAddressLine2",
  "customerShippingCity" = cu."shippingCity",
  "customerShippingProvince" = cu."shippingProvince",
  "customerShippingPostalCode" = cu."shippingPostalCode",
  "customerShippingCountry" = cu."shippingCountry"
FROM "companies" AS c, "customers" AS cu
WHERE i."companyId" = c."id"
  AND cu."id" = i."customerId";

UPDATE "estimates" AS e
SET
  "companyName" = c."companyName",
  "companyEmail" = c."email",
  "companyPhone" = c."phone",
  "companyWebsite" = c."website",
  "companyAddressLine1" = c."addressLine1",
  "companyAddressLine2" = c."addressLine2",
  "companyCity" = c."city",
  "companyProvince" = c."province",
  "companyPostalCode" = c."postalCode",
  "companyCountry" = c."country",
  "companyTaxNumber" = c."taxNumber",
  "customerName" = cu."name",
  "customerCompanyName" = cu."companyName",
  "customerEmail" = cu."email",
  "customerPhone" = cu."phone",
  "customerBillingAddressLine1" = cu."billingAddressLine1",
  "customerBillingAddressLine2" = cu."billingAddressLine2",
  "customerBillingCity" = cu."billingCity",
  "customerBillingProvince" = cu."billingProvince",
  "customerBillingPostalCode" = cu."billingPostalCode",
  "customerBillingCountry" = cu."billingCountry",
  "customerShippingSameAsBilling" = cu."shippingSameAsBilling",
  "customerShippingAddressLine1" = cu."shippingAddressLine1",
  "customerShippingAddressLine2" = cu."shippingAddressLine2",
  "customerShippingCity" = cu."shippingCity",
  "customerShippingProvince" = cu."shippingProvince",
  "customerShippingPostalCode" = cu."shippingPostalCode",
  "customerShippingCountry" = cu."shippingCountry"
FROM "companies" AS c, "customers" AS cu
WHERE e."companyId" = c."id"
  AND cu."id" = e."customerId";
